import { Layout } from "@/components/layout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Download, FileText, Search, Filter, Calendar } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useState } from "react";

// Mock data for reports
const MOCK_REPORTS = [
  { id: "RPT-2023-001", property: "Sunrise Heights, Wing A", date: "2023-11-15", type: "Full Audit", status: "COMPLETED", size: "2.4 MB" },
  { id: "RPT-2023-002", property: "Tech Park One - Office 304", date: "2023-10-01", type: "Risk Assessment", status: "COMPLETED", size: "1.1 MB" },
  { id: "RPT-2023-003", property: "Green Valley Plot 12", date: "2023-12-05", type: "Title Check", status: "COMPLETED", size: "3.5 MB" },
  { id: "RPT-2023-004", property: "Blue Ridge Apt 402", date: "2023-12-10", type: "Full Audit", status: "GENERATING", size: "-" },
  { id: "RPT-2023-005", property: "Commercial Complex - Shop 5", date: "2023-11-20", type: "Financial Due Diligence", status: "COMPLETED", size: "4.2 MB" },
];

export default function AuditReports() {
  const { toast } = useToast();
  const [searchQuery, setSearchQuery] = useState("");

  const handleDownload = (reportId: string) => {
    toast({
      title: "Downloading Report",
      description: `Starting download for ${reportId}...`,
    });
  };

  const filteredReports = MOCK_REPORTS.filter(r => 
    r.property.toLowerCase().includes(searchQuery.toLowerCase()) ||
    r.id.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <Layout>
      <div className="space-y-8">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Audit Reports</h1>
            <p className="text-muted-foreground mt-1">
              Access and manage all your generated property audit reports.
            </p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" className="gap-2">
              <Calendar className="h-4 w-4" /> Date Range
            </Button>
            <Button variant="outline" className="gap-2">
              <Filter className="h-4 w-4" /> Filter
            </Button>
            <Button className="gap-2">
              <FileText className="h-4 w-4" /> Generate New Report
            </Button>
          </div>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Report History</CardTitle>
            <CardDescription>
              A list of all audit reports generated by your team.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-4 mb-6">
              <div className="relative flex-1">
                <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search reports by property or ID..."
                  className="pl-9"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                />
              </div>
            </div>

            <div className="rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Report ID</TableHead>
                    <TableHead>Property</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Date Generated</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Size</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredReports.map((report) => (
                    <TableRow key={report.id}>
                      <TableCell className="font-medium font-mono text-xs">{report.id}</TableCell>
                      <TableCell>{report.property}</TableCell>
                      <TableCell>{report.type}</TableCell>
                      <TableCell>{report.date}</TableCell>
                      <TableCell>
                        <Badge variant={report.status === "COMPLETED" ? "secondary" : "outline"} className={
                          report.status === "COMPLETED" ? "bg-emerald-100 text-emerald-700 hover:bg-emerald-200" : "text-amber-600 border-amber-200"
                        }>
                          {report.status}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-muted-foreground text-sm">{report.size}</TableCell>
                      <TableCell className="text-right">
                        <Button 
                          variant="ghost" 
                          size="sm" 
                          disabled={report.status !== "COMPLETED"}
                          onClick={() => handleDownload(report.id)}
                        >
                          <Download className="h-4 w-4" />
                          <span className="sr-only">Download</span>
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
}
